### PR TITLE
add the 2.0 sample code and Composer support approach

### PR DESCRIPTION
**Pull request by peter279k**
It's for improving documentation in this [issue](https://github.com/phpseclib/phpseclib/issues/1202) comment.
# Changed log
- Add the Composer support approach
- Modify the sample code if installing the phpseclib via the Composer.
- Add the sample code of phpseclib 2.0.

I'm not sure that this changes is the good way.
Please review this and suggest the recommendation.
Then let me modify it.

Thanks.

### CODE REVIEW

**Comment by terrafrost** [comment]
**2.0.html**

I took your 2.0.html and put it at http://phpseclib.sourceforge.net/test.html to preview it out.

If you click on any of the links the backslashes for the namespaces go away, meaning that the PHP is invalid. Also, `echo $ssh->exec('pwd');` and `echo $ssh->exec('ls -la');` are both on one line when you click on the links.

For maintainability purposes I think the demo PHP scripts ought to be stored in a consistent manner. Like right now the default PHP script is stored thusly:

```html
<pre class="prettyprint">
...
</pre>
```

You're storing your stuff thusly:

```javascript
$('.prettyprint').html("...");
```

One could debate on which approach is the superior approach but I do think that a _consistent_ approach ought to be used to facilitate easier maintainability (to the exact that any of these approaches are really that maintainable at all)

Finally, altho phpseclib 2.0 is most often used with Composer, technically, Composer is not a dependency. This changes with phpseclib 3.0 but not 2.0. It might be worthwhile to mention that in your revised 2.0.html.

**rsa/examples.html**

So for this one I think it'd be better to maybe add another button on the left hand side. A "Use Composer" button that, when clicked, changes to "Don't Use Composer". Kinda like how the buttons on http://phpseclib.sourceforge.net/crypt/examples.html work. Then you wouldn't be displaying both `include 'Crypt/RSA.php'; // without Composer` and `require_once 'vendor/autoload.php'; // with Composer` concurrently - you'd just be displaying one at a time.

Also, I don't think the `\Crypt_RSA` bit is necessary. Consider php.net's documentation on `DateTime`:

http://php.net/manual/en/datetime.construct.php#refsect1-datetime.construct-examples

It uses `DateTime` - not `\DateTime`.

**Comment by peter279k** [comment]
Hi @terrafrost, thank you for reply.
- The ```\DateTime``` because of the namespace. we use the ```DateTime``` and it will be identified by the one of specified namespace. But this time is not presented any ```namespace``` so using the ```DateTime``` is fine.
- How can I build the documentation locally? When I complete the sample code, I can't preview my result. I try to use the web browser to present the results directly, but it presents lots of error messages in the web browser console.
Can you provide the building doc tutorial?

Thanks.

**Comment by peter279k** [comment]
Maybe we can just use the GitHub wiki directly?

**Comment by terrafrost** [comment]
> The ```\DateTime``` because of the namespace. we use the ```DateTime``` and it will be identified by the one of specified namespace. But this time is not presented any ```namespace``` so using the ```DateTime``` is fine.

I get that but just as the `DateTime` examples aren't being utilized in a namespace neither are the phpseclib examples.

> How can I build the documentation locally? When I complete the sample code, I can't preview my result. I try to use the web browser to present the results directly, but it presents lots of error messages in the web browser console.
> Can you provide the building doc tutorial?

I don't really build them. idk what types of errors you're getting but my guess is that maybe you don't have the relative paths setup? Like a lot of the files have stuff like this:

```html
<link rel="stylesheet" href="../css/reset.css" />

<link rel="stylesheet" href="../css/text.css" />
<link rel="stylesheet" href="../css/960.css" />
<link rel="stylesheet" href="../css/prettify.css"/>

<script src="../js/prettify.js"></script>
<script src="../js/jquery-1.7.2.min.js"></script>
```

> Perhaps we can use the [readthedocs](https://readthedocs.org/) to create the documentation.
Like[ Guzzle](http://docs.guzzlephp.org/en/latest/) doc.
>
> Maybe we can just use the GitHub wiki or [page](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages) directly?

I'm completely on-board with that. In my private notes here are two docs that I liked:

https://irazasyed.github.io/telegram-bot-sdk/
http://expressjs.com/

I was thinking I might try to do that for the release of 3.0 but, realistically speaking, idk that that'll be happening even next year. Lots of work to do on that and, right now, I'd just assume spend any free time I have working on 3.0 - not on documentation.

If this is something you want to work on...  I can create a docs2 repo or some such in https://github.com/phpseclib/ and give you commit access. Just keep in mind that my main focus is, like I said, 3.0 and not documentation. At least for the time being.

**Comment by peter279k** [comment]
Hi @terrafrost, thank you for your reply. I've known that you focus on the 3.0 version at this time.
The documentation I can contribute that. Even the the future version 3.0 doc,
I also prefer the [telegram-bot-sdk](https://irazasyed.github.io/telegram-bot-sdk/) doc.
You can create the ```doc2``` repo for me and I will be responsible for the phpseclib doc.

Thanks.

**Comment by terrafrost** [comment]
I created the repo and added you as a collaborator!

**Comment by peter279k** [comment]
Closed because the  v3.0 is available now.

**Pull request closed without merging**
